server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jscdb;DB_CLOSE_DELAY=-1
    username: jsc2
    password: jsc02
    platform: h2
  h2:
    console:
      enabled: true
      path: /db
      settings:
        web-allow-others: true
        trace: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    drop-first: true
    change-log: classpath:db/changelog/master.xml
    enabled: true
